name: game_collection
description: A simple and intuitive game collection manager.
version: 2.4.0+249
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # BLoC pattern
  flutter_bloc: ^8.0.0

  # Back-end
  backend:
    path: ./backend

  # Front-end
  smooth_star_rating:
    git:
      url: https://github.com/viplmad/smoothratingbar.git
      ref: dev
  numberpicker: ^2.0.0
  image_picker: ^0.8.0
  cached_network_image: ^3.0.0
  url_launcher: ^6.0.2
  flutter_launcher_icons: ^0.9.0
  table_calendar: ^3.0.0
  flutter_speed_dial: ^5.0.0+1
  duration_picker: ^1.0.1
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/icon_background.png"
  adaptive_icon_foreground: "assets/images/icon_foreground.png"

flutter:
  uses-material-design: true