name: game_collection
description: A simple and intuitive game collection manager.
version: 3.1.1+338
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2

  async: ^2.0.0

  # BLoC pattern
  flutter_bloc: ^8.1.1

  # Front-end
  smooth_star_rating:
    git:
      url: https://github.com/viplmad/smoothratingbar.git
      ref: dev
  image_picker: ^0.8.0
  cached_network_image: ^3.2.2
  url_launcher: ^6.1.5
  table_calendar: ^3.0.7
  flutter_speed_dial: ^6.0.0
  duration_picker: ^1.0.1
  community_charts_flutter: ^1.0.1
  package_info_plus: ^4.0.0

# Back-end
  logic:
    path: ./logic
  game_collection_client:
    git:
      url: https://github.com/viplmad/game_collection_client_dart.git
      ref: main

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  min_sdk_android: 28
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/icon_background.png"
  adaptive_icon_foreground: "assets/images/icon_foreground.png"

flutter:
  uses-material-design: true

  # Necessary for localisation
  generate: true

  assets:
    - assets/images/icon.png
