name: backend
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  meta: ^1.3.0

  # BLoC pattern
  bloc: ^7.0.0
  equatable: ^2.0.0

  # Encrypted shared preferences
  encrypted_shared_preferences:  ^2.0.0

  # Database and Image connection
  postgres: ^2.3.0
  cloudinary_client:
    git: https://github.com/viplmad/cloudinary_client.git
  http: ^0.13.0
  query:
    path: ../query

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
