name: backend
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=3.3.10"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.7.0

  # BLoC pattern
  bloc: ^8.0.2
  equatable: ^2.0.0

  # Package Info
  package_info_plus: ^3.0.2

  # Encrypted shared preferences
  encrypted_shared_preferences: ^3.0.0

  # Client
  game_collection_client:
    path: ../../game_collection_client

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter