name: backend
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.7.0

  # BLoC pattern
  bloc: ^8.0.2
  equatable: ^2.0.0

  # Package Info
  package_info_plus: ^1.4.2

  # Encrypted shared preferences
  encrypted_shared_preferences: ^3.0.0

  # Database and Image connection
  postgres: ^2.3.0
  cloudinary_client:
    git: https://github.com/viplmad/cloudinary_client.git
  http: ^0.13.0
  query:
    path: ../query

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter