name: query
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec