name: logic
version: 3.0.0
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.11.0

  # BLoC pattern
  bloc: ^8.0.2
  equatable: ^2.0.0

  # Package Info
  package_info_plus: ^8.0.0

  # Encrypted shared preferences
  encrypted_shared_preferences: ^3.0.0

  # Client
  http: ^1.1.0
  game_oclock_client:
    git:
      url: https://github.com/viplmad/game-oclock-client-dart.git
      ref: v1.4.0+70

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
