name: logic
version: 2.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.7.0

  # BLoC pattern
  bloc: ^8.0.2
  equatable: ^2.0.0

  # Package Info
  package_info_plus: ^4.0.0

  # Encrypted shared preferences
  encrypted_shared_preferences: ^3.0.0

  # Client
  http: ^0.13.0
  game_collection_client:
    git:
      url: https://github.com/viplmad/game_collection_client_dart.git
      ref: main

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter