site_name: Game o'Clock documentation
site_description: Documentation for Game o'Clock
site_author: Vicent Pla
copyright: "&copy; <span>Vicent Pla</span>, licensed under <a href=\"https://github.com/viplmad/game-oclock_docs/blob/main/license\">Attribution-ShareAlike 4.0 International</a>."
repo_url: https://github.com/viplmad/game-oclock/
edit_uri: https://github.com/viplmad/game-oclock/tree/main/docs/
site_url: https://viplmad.github.io/game-oclock/
dev_addr: '127.0.0.1:8000'

theme:
  font: false
  name: material
  custom_dir: overrides

nav:
  - Home: index.md
  - App:
    - Home: app/index.md
  - Server:
    - Home: server/index.md
  - Client:
    - Home: client/index.md